#!/usr/bin/bash

# Author: 3urobeat (https://github.com/HerrEurobeat)
# Description: Gets the amount of available package updates (+AUR). Click the block to see which packages can be updated (notification).
# Disclaimer: Needs 'checkupdates+aur' package from the AUR to work.

# send notification before checking when clicked so the user knows the click was recognized
if [[ $BLOCK_BUTTON -eq 1 ]]; then
    $(notify-send checkupdates "Checking available updates...")
fi

PACKAGES=$(checkupdates)

# check if no updates were found so that 'wc -l' doesn't respond with '1'
if [[ $PACKAGES == "" ]]; then
    echo 0
    echo 0
else
    COUNT=$(echo "$PACKAGES" | wc -l) # quotes around var preserves new lines

    echo $COUNT
    echo $COUNT
fi

# show notification with updateable packages when clicked
if [[ $BLOCK_BUTTON -eq 1 ]]; then

    # show different message if no updates were found
    if [[ $PACKAGES == "" ]]; then
        $(notify-send checkupdates "No available updates found.")
    else
        $(notify-send checkupdates "$PACKAGES")
    fi
fi
